// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropertyManagement.API.Data;

#nullable disable

namespace PropertyManagement.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropertyManagement.API.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsExported")
                        .HasColumnType("bit");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Invoices", (string)null);

                    b.HasData(
                        new
                        {
                            InvoiceId = 1,
                            InvoiceDate = new DateTime(2026, 1, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsExported = true,
                            ProjectId = 1,
                            Status = "Paid",
                            TotalAmount = 150m
                        },
                        new
                        {
                            InvoiceId = 2,
                            InvoiceDate = new DateTime(2026, 2, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsExported = false,
                            ProjectId = 2,
                            Status = "Sent",
                            TotalAmount = 400m
                        },
                        new
                        {
                            InvoiceId = 3,
                            InvoiceDate = new DateTime(2026, 4, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsExported = false,
                            ScheduleId = 2,
                            Status = "Overdue",
                            TotalAmount = 1250m
                        },
                        new
                        {
                            InvoiceId = 4,
                            InvoiceDate = new DateTime(2026, 1, 13, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsExported = true,
                            ProjectId = 6,
                            Status = "Paid",
                            TotalAmount = 100m
                        });
                });

            modelBuilder.Entity("PropertyManagement.API.Models.MaintenanceProject", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("AssignedVendor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("BidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProjectTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProjectId");

                    b.HasIndex("PropertyId");

                    b.ToTable("MaintenanceProjects", (string)null);

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            AssignedVendor = "Fix-It Plumbing",
                            BidAmount = 150m,
                            ProjectTitle = "Broken Faucet",
                            PropertyId = 1,
                            Status = "Closed"
                        },
                        new
                        {
                            ProjectId = 2,
                            AssignedVendor = "Pro Painters",
                            BidAmount = 400m,
                            ProjectTitle = "Paint Bedroom",
                            PropertyId = 2,
                            Status = "Invoiced"
                        },
                        new
                        {
                            ProjectId = 3,
                            AssignedVendor = "CoolAir Inc",
                            BidAmount = 800m,
                            ProjectTitle = "AC Repair",
                            PropertyId = 3,
                            Status = "Work Order"
                        },
                        new
                        {
                            ProjectId = 4,
                            AssignedVendor = "TopRoofing",
                            BidAmount = 2500m,
                            ProjectTitle = "Roof Leak",
                            PropertyId = 4,
                            Status = "Bid"
                        },
                        new
                        {
                            ProjectId = 5,
                            AssignedVendor = "Janitor Pro",
                            BidAmount = 300m,
                            ProjectTitle = "Floor Buffing",
                            PropertyId = 5,
                            Status = "Approved"
                        },
                        new
                        {
                            ProjectId = 6,
                            AssignedVendor = "SafeLocks",
                            BidAmount = 100m,
                            ProjectTitle = "Door Lock Fix",
                            PropertyId = 6,
                            Status = "Closed"
                        });
                });

            modelBuilder.Entity("PropertyManagement.API.Models.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("MonthlyRent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PropertyName");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PropertyId");

                    b.ToTable("Properties", (string)null);

                    b.HasData(
                        new
                        {
                            PropertyId = 1,
                            Address = "123 Maple St",
                            MonthlyRent = 1200m,
                            Name = "Sunrise Apts",
                            UnitNumber = "1A"
                        },
                        new
                        {
                            PropertyId = 2,
                            Address = "123 Maple St",
                            MonthlyRent = 1250m,
                            Name = "Sunrise Apts",
                            UnitNumber = "1B"
                        },
                        new
                        {
                            PropertyId = 3,
                            Address = "456 Oak Ave",
                            MonthlyRent = 2000m,
                            Name = "Oak Estates",
                            UnitNumber = "Unit 10"
                        },
                        new
                        {
                            PropertyId = 4,
                            Address = "456 Oak Ave",
                            MonthlyRent = 2100m,
                            Name = "Oak Estates",
                            UnitNumber = "Unit 11"
                        },
                        new
                        {
                            PropertyId = 5,
                            Address = "789 River Rd",
                            MonthlyRent = 1500m,
                            Name = "River View",
                            UnitNumber = "302"
                        },
                        new
                        {
                            PropertyId = 6,
                            Address = "789 River Rd",
                            MonthlyRent = 1550m,
                            Name = "River View",
                            UnitNumber = "303"
                        });
                });

            modelBuilder.Entity("PropertyManagement.API.Models.PropertyApplication", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<string>("ApplicantFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApplicantLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CurrentEmployer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HouseholdSize")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PetsDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("PreferredMoveInDate")
                        .HasColumnType("date");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ApplicationId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyApplications", (string)null);
                });

            modelBuilder.Entity("PropertyManagement.API.Models.RentPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("RentPayments", (string)null);

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            AmountPaid = 1200m,
                            PaymentDate = new DateTime(2026, 3, 31, 10, 30, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "ACH",
                            ScheduleId = 1,
                            TransactionRef = "ACH-1001"
                        },
                        new
                        {
                            PaymentId = 2,
                            AmountPaid = 1500m,
                            PaymentDate = new DateTime(2026, 3, 31, 11, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Card",
                            ScheduleId = 5,
                            TransactionRef = "CARD-1005"
                        },
                        new
                        {
                            PaymentId = 3,
                            AmountPaid = 500m,
                            PaymentDate = new DateTime(2026, 4, 2, 9, 15, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Card",
                            ScheduleId = 6,
                            TransactionRef = "CARD-1006"
                        });
                });

            modelBuilder.Entity("PropertyManagement.API.Models.RentSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<decimal>("BaseRent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal>("LateFeeAccrued")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReminderCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.HasIndex("TenantId");

                    b.ToTable("RentSchedules", (string)null);

                    b.HasData(
                        new
                        {
                            ScheduleId = 1,
                            BaseRent = 1200m,
                            DueDate = new DateOnly(2026, 4, 1),
                            LateFeeAccrued = 0m,
                            ReminderCount = 0,
                            Status = "Paid",
                            TenantId = 1
                        },
                        new
                        {
                            ScheduleId = 2,
                            BaseRent = 1250m,
                            DueDate = new DateOnly(2026, 4, 1),
                            LateFeeAccrued = 0m,
                            ReminderCount = 1,
                            Status = "Unpaid",
                            TenantId = 2
                        },
                        new
                        {
                            ScheduleId = 3,
                            BaseRent = 2000m,
                            DueDate = new DateOnly(2026, 4, 1),
                            LateFeeAccrued = 150m,
                            ReminderCount = 3,
                            Status = "Late",
                            TenantId = 3
                        },
                        new
                        {
                            ScheduleId = 4,
                            BaseRent = 2100m,
                            DueDate = new DateOnly(2026, 4, 1),
                            LateFeeAccrued = 0m,
                            ReminderCount = 0,
                            Status = "Unpaid",
                            TenantId = 4
                        },
                        new
                        {
                            ScheduleId = 5,
                            BaseRent = 1500m,
                            DueDate = new DateOnly(2026, 4, 1),
                            LateFeeAccrued = 0m,
                            ReminderCount = 0,
                            Status = "Paid",
                            TenantId = 5
                        },
                        new
                        {
                            ScheduleId = 6,
                            BaseRent = 1550m,
                            DueDate = new DateOnly(2026, 4, 1),
                            LateFeeAccrued = 50m,
                            ReminderCount = 2,
                            Status = "Partial",
                            TenantId = 6
                        });
                });

            modelBuilder.Entity("PropertyManagement.API.Models.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("TenantId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Tenants", (string)null);

                    b.HasData(
                        new
                        {
                            TenantId = 1,
                            Email = "john@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "555-0101",
                            PropertyId = 1
                        },
                        new
                        {
                            TenantId = 2,
                            Email = "jane@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PhoneNumber = "555-0102",
                            PropertyId = 2
                        },
                        new
                        {
                            TenantId = 3,
                            Email = "mike@example.com",
                            FirstName = "Mike",
                            LastName = "Jones",
                            PhoneNumber = "555-0103",
                            PropertyId = 3
                        },
                        new
                        {
                            TenantId = 4,
                            Email = "sarah@example.com",
                            FirstName = "Sarah",
                            LastName = "Wilson",
                            PhoneNumber = "555-0104",
                            PropertyId = 4
                        },
                        new
                        {
                            TenantId = 5,
                            Email = "alex@example.com",
                            FirstName = "Alex",
                            LastName = "Brown",
                            PhoneNumber = "555-0105",
                            PropertyId = 5
                        },
                        new
                        {
                            TenantId = 6,
                            Email = "chris@example.com",
                            FirstName = "Chris",
                            LastName = "Davis",
                            PhoneNumber = "555-0106",
                            PropertyId = 6
                        });
                });

            modelBuilder.Entity("PropertyManagement.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PropertyManagement.API.Models.WorkLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("ClockInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ClockOutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("GpsLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaterialsUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ProofPhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorSignature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.HasIndex("ProjectId");

                    b.ToTable("WorkLogs", (string)null);

                    b.HasData(
                        new
                        {
                            LogId = 1,
                            ClockInTime = new DateTime(2026, 1, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            ClockOutTime = new DateTime(2026, 1, 10, 10, 30, 0, 0, DateTimeKind.Utc),
                            GpsLocation = "34.05,-118.24",
                            MaterialsUsed = "Replacement faucet kit",
                            ProjectId = 1,
                            ProofPhotoUrl = "img01.jpg",
                            VendorSignature = "Fix-It Plumbing"
                        },
                        new
                        {
                            LogId = 2,
                            ClockInTime = new DateTime(2026, 1, 12, 14, 0, 0, 0, DateTimeKind.Utc),
                            ClockOutTime = new DateTime(2026, 1, 12, 14, 45, 0, 0, DateTimeKind.Utc),
                            GpsLocation = "34.06,-118.25",
                            MaterialsUsed = "Lock cylinder",
                            ProjectId = 6,
                            ProofPhotoUrl = "img02.jpg",
                            VendorSignature = "SafeLocks"
                        },
                        new
                        {
                            LogId = 3,
                            ClockInTime = new DateTime(2026, 4, 3, 8, 30, 0, 0, DateTimeKind.Utc),
                            ClockOutTime = new DateTime(2026, 4, 3, 11, 0, 0, 0, DateTimeKind.Utc),
                            GpsLocation = "34.07,-118.22",
                            MaterialsUsed = "Coolant and fan motor",
                            ProjectId = 3,
                            ProofPhotoUrl = "ac-repair.jpg",
                            VendorSignature = "CoolAir Inc"
                        });
                });

            modelBuilder.Entity("PropertyManagement.API.Models.Invoice", b =>
                {
                    b.HasOne("PropertyManagement.API.Models.MaintenanceProject", "Project")
                        .WithMany("Invoices")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PropertyManagement.API.Models.RentSchedule", "Schedule")
                        .WithMany("Invoices")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("PropertyManagement.API.Models.MaintenanceProject", b =>
                {
                    b.HasOne("PropertyManagement.API.Models.Property", "Property")
                        .WithMany("MaintenanceProjects")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyManagement.API.Models.PropertyApplication", b =>
                {
                    b.HasOne("PropertyManagement.API.Models.Property", "Property")
                        .WithMany("Applications")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyManagement.API.Models.RentPayment", b =>
                {
                    b.HasOne("PropertyManagement.API.Models.RentSchedule", "RentSchedule")
                        .WithMany("RentPayments")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentSchedule");
                });

            modelBuilder.Entity("PropertyManagement.API.Models.RentSchedule", b =>
                {
                    b.HasOne("PropertyManagement.API.Models.Tenant", "Tenant")
                        .WithMany("RentSchedules")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyManagement.API.Models.Tenant", b =>
                {
                    b.HasOne("PropertyManagement.API.Models.Property", "Property")
                        .WithMany("Tenants")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyManagement.API.Models.WorkLog", b =>
                {
                    b.HasOne("PropertyManagement.API.Models.MaintenanceProject", "Project")
                        .WithMany("WorkLogs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PropertyManagement.API.Models.MaintenanceProject", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("WorkLogs");
                });

            modelBuilder.Entity("PropertyManagement.API.Models.Property", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("MaintenanceProjects");

                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("PropertyManagement.API.Models.RentSchedule", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("RentPayments");
                });

            modelBuilder.Entity("PropertyManagement.API.Models.Tenant", b =>
                {
                    b.Navigation("RentSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
